# This config is used to evaluate a feature for every kernel
figure:
    # colors: {'control_stalls': 'xkcd:green', 'scoreboard_stalls':'xkcd:orange',
    #         'pipeline_stalls': 'xkcd:sky blue'}
    colors: ['xkcd:light blue', 'xkcd:blue', 'xkcd:light orange', 'xkcd:orange',
             'xkcd:light green', 'xkcd:green', 'xkcd:light red', 'xkcd:red',
             'xkcd:light purple', 'xkcd:purple', 'xkcd:light brown', 'xkcd:brown',
             'xkcd:light pink', 'xkcd:pink', 'xkcd:light grey', 'xkcd:grey']
    figure:
        nrows: 1
        ncols: 3
        sharex: 'all'
        sharey: 'row'
        figsize: [5,1.5]
    ticks:
        x:
            fontsize: '10'
        y: 
            fontsize: '10'
    legend:
        loc: 'upper left'
        ncol: 1
        handlelength: 1
        fancybox: True
        framealpha: 0.3
        frameon: False
        fontsize: 10
        labelspacing: 0
        borderpad: 0.5
        handletextpad: 0.5
        borderaxespad: 0
    subplots_adjust:
        wspace: 0.1
        hspace: 0.1
        top: 0.95
    tick_params:
        pad: 1
        top: 0
        bottom: 1
        left: 1
        direction: 'inout'
        length: 2
        width: 0.5
    suptitle:
        fontsize: 10
    title:
        fontsize: 10
phases: ['comm', 'comp', 'serial']